env:
  - GO111MODULE=on
  - LINUXBENCH_CFG=/etc/linux-bench/cfg
builds:
  - main: .
    binary: linux-bench
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
     - "-X github.com/aquasecurity/linux-bench/root.cfgDir={{.Env.LINUXBENCH_CFG}}"
# Archive customization
archives:
  - id: compress
    format: tar.gz
    files:
      - "cfg/**/*"
nfpms:
  - vendor: Aqua Security
    description: "Linux-bench checks whether a Linux server according to security best practices as defined in the CIS Distribution-Independent Linux Benchmark"
    license: Apache-2.0
    homepage: https://github.com/aquasecurity/linux-bench
    files:
      "cfg/**/*": "/etc/linux-bench/cfg"
    formats:
      - deb
      - rpm
